name = "MyExamplePackage"
uuid = "b3020622-1135-4445-b713-3b3452ffd7c0"
authors = ["Ben Kincaid"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
